### ISSUE TITLE
Feature Request: Option of switching out Apple emojis for other emojis

### ISSUE THREAD

**Issue by theolice** [johannhof/emoji-helper#74] opened 2016-08-01 08:51 UTC
Is it possible to give us the option to switch to other emoji styles?

I personally prefer the Google emojis over the Apple ones.

Nobody has done this before and I think it would  be a great asset if people see that they have the freedom to choose which emoji styles they prefer :dog2:

**Comment by johannhof** [comment] 2017-07-09 13:14
Dupe of #34

**Closed by johannhof** 2017-07-09 13:14 UTC
Labels: new feature
