### ISSUE TITLE
Firefox - color emoji

### ISSUE THREAD

**Issue by ajax659** [johannhof/emoji-helper#41] opened 2015-05-28 14:42 UTC
When I use the drop down to select an emoji, it is in color, but no matter what I do, when I select it to paste into Twitter it is in black and white only?

**Comment by mikhoul** [comment] 2015-05-28 17:11
It depend if the Emoji is supported or not.  Personnaly for Twitter I use this UserScript: https://greasyfork.org/en/scripts/7981-emoji-twitter  it is integrated in the Twitter interface.

N.B.: Don't forget to install Greasemonkey before if you want try it. https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

![zzz_2015-05-28_13-07-09](https://cloud.githubusercontent.com/assets/5678673/7866067/f71276ea-053a-11e5-942a-04d5cba28281.png)

**Comment by Croydon** [comment] 2016-08-30 00:54
This is not a bug of the add-on. Twitter doesn't instantly give a graphical view of it and none at all if it is not supported. If it is not supported the character/letter/symbol (unicode) will be displayed like everyone else (black).

**Comment by elamperti** [comment] 2017-03-12 22:17
Twitter now displays emoji using their own mechanism and they even have their own picker.
@ajax659 this issue should be resolved now, please close it if you can! :)

**Closed** 2017-07-09 13:13 UTC
Labels: bug
